SELECT  DOM.STADIUM_NAME STADIUM_NAME, TO_CHAR(TO_DATE(S.SCHE_DATE, 'YYYYMMDD'), 'YYYY"년"MM"월"DD"일"') SCHE_DATE, 
            HT.TEAM_NAME HOMETEAM_NAME, S.HOME_SCORE HOMETEAM_SCORE, 
            AT.TEAM_NAME AWAYTEAM_NAME, S.AWAY_SCORE AWAYTEAM_SCORE
    FROM    TEAM HT, SCHEDULE S, TEAM AT, STADIUM DOM
    WHERE   HT.TEAM_ID = S.HOMETEAM_ID
    AND     AT.TEAM_ID = S.AWAYTEAM_ID
    AND     DOM.STADIUM_ID = S.STADIUM_ID
    AND    (S.HOME_SCORE IS NOT NULL
    OR      S.AWAY_SCORE IS NOT NULL)
    ORDER BY S.SCHE_DATE DESC, DOM.STADIUM_NAME; 
    
    
    
--inner join을 사용하면 where절의 is not null or is not null 을 연결할때 괄호가 없어도 된다


