 CREATE OR REPLACE PROCEDURE P_SEL_K_LEAGUE_SCHE
(I_STADIUM_NAME IN VARCHAR2, I_SCHE_DATE IN VARCHAR2,
 V_STADIUM_NAME OUT VARCHAR2, V_SCHE_DATE OUT VARCHAR2,
 V_HOMETEAM_NAME OUT VARCHAR2, V_HOMETEAM_SCORE OUT NUMBER,
 V_AWAYTEAM_NAME OUT VARCHAR2, V_AWAYTEAM_SCORE OUT NUMBER)
IS
BEGIN
    SELECT  DOM.STADIUM_NAME STADIUM_NAME, TO_CHAR(TO_DATE(S.SCHE_DATE, 'YYYYMMDD'), 'YYYY"년"MM"월"DD"일"') SCHE_DATE, 
            HT.TEAM_NAME HOMETEAM_NAME, S.HOME_SCORE HOMETEAM_SCORE, 
            AT.TEAM_NAME AWAYTEAM_NAME, S.AWAY_SCORE AWAYTEAM_SCORE 
                                                                     INTO V_STADIUM_NAME, V_SCHE_DATE,
                                                                    V_HOMETEAM_NAME, V_HOMETEAM_SCORE,
                                                                    V_AWAYTEAM_NAME, V_AWAYTEAM_SCORE
    FROM    TEAM HT, SCHEDULE S, TEAM AT, STADIUM DOM
    WHERE   HT.TEAM_ID = S.HOMETEAM_ID
    AND     AT.TEAM_ID = S.AWAYTEAM_ID
    AND     DOM.STADIUM_ID = S.STADIUM_ID
    AND    (S.HOME_SCORE IS NOT NULL
    OR      S.AWAY_SCORE IS NOT NULL)
    AND     DOM.STADIUM_NAME = I_STADIUM_NAME
    AND     SCHE_DATE = I_SCHE_DATE
    ORDER BY S.SCHE_DATE DESC, DOM.STADIUM_NAME;
END;
/

