--SET SERVEROUTPUT ON;
--
--DECLARE
-- V_ENAME VARCHAR2(100);
-- V_SAL NUMBER;
--BEGIN
-- SEL_EMPNO(7499, V_ENAME, V_SAL); 
-- DBMS_OUTPUT.PUT_LINE(V_ENAME || ' : ' || V_SAL);
--END;
--/
--
--SELECT *
--FROM EMP01;
--
--
--VARIABLE VAR_ENAME VARCHAR2;
--VARIABLE VAR_SAL NUMBER;
--
--EXECUTE SEL_EMPNO(73639, :VAR_ENAME, :VAR_SAL); 
--
--PRINT VAR_ENAME VAR_SAL;


--VARIABLE V_STADIUM_NAME VARCHAR2;
--VARIABLE V_SCHE_DATE VARCHAR2;
--VARIABLE V_HOMETEAM_NAME VARCHAR2;
--VARIABLE V_HOMETEAM_SCORE NUMBER;
--VARIABLE V_AWAYTEAM_NAME VARCHAR2;
--VARIABLE V_AWAYTEAM_SCORE NUMBER;
--
--
--EXECUTE P_SEL_K_LEAGUE_SCHE('부산아시아드경기장', '20120904', :V_STADIUM_NAME, :V_SCHE_DATE, :V_HOMETEAM_NAME, :V_HOMETEAM_SCORE, :V_AWAYTEAM_NAME, :V_AWAYTEAM_SCORE);

SET SERVEROUTPUT ON;

DECLARE
 V_STADIUM_NAME VARCHAR2(100);
 V_SCHE_DATE VARCHAR2(100);
 V_HOMETEAM_NAME VARCHAR2(100);
 V_HOMETEAM_SCORE NUMBER;
 V_AWAYTEAM_NAME VARCHAR2(100);
 V_AWAYTEAM_SCORE NUMBER;
BEGIN
 P_SEL_K_LEAGUE_SCHE('부산아시아드경기장', '20120904', V_STADIUM_NAME, V_SCHE_DATE, 
    V_HOMETEAM_NAME, V_HOMETEAM_SCORE, V_AWAYTEAM_NAME, V_AWAYTEAM_SCORE);
 DBMS_OUTPUT.PUT_LINE(V_STADIUM_NAME || ' : ' || V_SCHE_DATE || ' : ' || V_HOMETEAM_NAME || ' : ' 
            || V_HOMETEAM_SCORE || ' : ' || V_AWAYTEAM_NAME || ' : ' || V_AWAYTEAM_SCORE);
END;
/                     -- 슬래시가 실행하라는 명령어