--MEMBER 테이블 생성
create table MEMBER(
    MEMBER_NO NUMBER NOT NULL,
    STATUS NUMBER NOT NULL,
    AUTHORITY VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    ID VARCHAR2(30) NOT NULL,
    PASSWORD VARCHAR2(30) NOT NULL,
    ADRESS VARCHAR2(100) NOT NULL,
    HP VARCHAR2(30) NOT NULL,
    CRE_DATE DATE NOT NULL,
    MOD_DATE DATE NOT NULL
);

--MEMBER_NO 기본키 제약조건
ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_NO_PK PRIMARY KEY (MEMBER_NO);

--MEMBER_ID 유니크 제약조건
ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_ID_UK UNIQUE(ID);

--시퀀스 생성
CREATE SEQUENCE MEMBER_NO_SEQ
INCREMENT BY 1
START WITH 1;

--MEMBER 테이블 보기
SELECT *
FROM MEMBER;


--상품 테이블 제작
CREATE TABLE PRODUCT(
    PRODUCT_NO NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    QUANTITY NUMBER NOT NULL,
    PRICE NUMBER NOT NULL,
    DETAIL VARCHAR2(1000) NOT NULL,
    ORIGINAL_FILE_NAME VARCHAR2(260) NOT NULL,
    STORED_FILE_NAME VARCHAR2(40) NOT NULL,
    FILE_SIZE NUMBER NOT NULL,
    ENROLLMENT_DATE DATE NOT NULL
);

--상품번호 기본키 제약조건
ALTER TABLE PRODUCT
ADD CONSTRAINT PRODUCT_NO_PK PRIMARY KEY (PRODUCT_NO);

--시퀀스 생성
CREATE SEQUENCE PRODUCT_NO_SEQ
INCREMENT BY 1
START WITH 1;

-- 상품테이블 보기
SELECT *
FROM PRODUCT;


--거래목록 리스트 생성
CREATE TABLE PURCHASE_LIST(
    PURCHASE_LIST_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    PRODUCT_SIZE VARCHAR2(5) NOT NULL,
    PURCHASE_DATE DATE NOT NULL,
    REQUESTS VARCHAR2(500),
    ADRESS VARCHAR2(100) NOT NULL
);

ALTER TABLE PURCHASE_LIST
ADD REQUESTS VARCHAR2(500);

ALTER TABLE PURCHASE_LIST
ADD ADRESS VARCHAR2(100);

ALTER TABLE PURCHASE_LIST
MODIFY (ADRESS NOT NULL);



--구매목록 번호 기본키
ALTER TABLE PURCHASE_LIST
ADD CONSTRAINT PURCHASE_LIST_NO_PK PRIMARY KEY (PURCHASE_LIST_NO);

--시퀀스 생성
CREATE SEQUENCE PURCHASE_NO_SEQ
INCREMENT BY 1
START WITH 1;

--구매목록 테이블 보기
SELECT *
FROM PURCHASE_LIST;

--외래키 설정
alter table PURCHASE_LIST add constraint PURCHASE_LIST_MEMBER_NO_MEMBER foreign key(MEMBER_NO) 
references MEMBER (MEMBER_NO);

alter table PURCHASE_LIST add constraint PURCHASE_LIST_NO_PRODUCT_FK foreign key(PRODUCT_NO) 
references PRODUCT (PRODUCT_NO);



commit;
--데이터를 넣어보고 테스트 해봐